package com.example.geektrust.constants;

public enum Status {
    ADD_SUBSCRIPTION_FAILED_INVALID_DATE("ADD_SUBSCRIPTION_FAILED INVALID_DATE"),
    ADD_TOPUP_FAILED_INVALID_DATE("ADD_TOPUP_FAILED INVALID_DATE"),
    ADD_SUBSCRIPTION_FAILED_DUPLICATE_CATEGORY("ADD_SUBSCRIPTION_FAILED DUPLICATE_CATEGORY"),
    ADD_TOPUP_FAILED_DUPLICATE_TOPUP("ADD_TOPUP_FAILED DUPLICATE_TOPUP"),
    SUBSCRIPTIONS_NOT_FOUND("SUBSCRIPTIONS_NOT_FOUND"),
    ERROR_INVALID_DATE("INVALID_DATE"),
    ADD_TOPUP_FAILED_SUBSCRIPTIONS_NOT_FOUND("ADD_TOPUP_FAILED SUBSCRIPTIONS_NOT_FOUND"),

    NO_ERROR("NO_ERROR");

    private final String value;

    Status(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}